# Tensor

## Import dependencies

In [6]:
import torch
import numpy as np

## Challenge series 1: 
- Create and Manipulate Tensors
- Create a random tensor of shape (3, 3) and print its values.
- Create a zero tensor and a ones tensor of shape (2, 4).
- Convert a NumPy array to a PyTorch tensor and vice versa.

In [19]:
tensor = torch.rand( (3,5),dtype=torch.float16)
print(tensor.add_(5).shape)
tensor.add_(5) @ tensor.T

torch.Size([3, 5])


tensor([[552.5000, 556.5000, 548.5000],
        [556.5000, 561.0000, 552.5000],
        [548.5000, 552.5000, 544.5000]], dtype=torch.float16)

In [20]:
tensor = torch.rand( (3,3),dtype=torch.float16)
tensor

tensor([[0.8677, 0.3369, 0.0054],
        [0.9644, 0.2407, 0.1479],
        [0.7466, 0.4185, 0.7451]], dtype=torch.float16)

In [28]:
ones = torch.ones( (3,6),dtype=torch.int)
zeros = torch.zeros_like(ones, dtype= torch.float16)
zeros + ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float16)

In [57]:
n = np.array((3,5), dtype=np.float16)
t = torch.from_numpy(n)
n = t.numpy()